In [34]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
np.set_printoptions(formatter={'complex_kind': '{: .3f}'.format})

In [35]:
given_array = np.array([1,1,1,1,1,1,0,0], dtype=np.float32)

In [36]:
given_array

array([1., 1., 1., 1., 1., 1., 0., 0.], dtype=float32)

In [37]:
dft_by_cv = cv2.dft(given_array.astype(np.float32), flags=cv2.DFT_COMPLEX_OUTPUT)

In [38]:
dft_by_cv

array([[[ 6.        ,  0.        ]],

       [[-0.70710677, -1.7071068 ]],

       [[ 1.        , -1.        ]],

       [[ 0.70710677,  0.29289323]],

       [[ 0.        ,  0.        ]],

       [[ 0.70710677, -0.29289323]],

       [[ 1.        ,  1.        ]],

       [[-0.70710677,  1.7071068 ]]], dtype=float32)

In [39]:
dft_results_by_cv2 = np.vectorize(complex)(dft_by_cv[:,:,0],dft_by_cv[:,:,1])

In [40]:
dft_results_by_cv2

array([[ 6.000+0.000j],
       [-0.707-1.707j],
       [ 1.000-1.000j],
       [ 0.707+0.293j],
       [ 0.000+0.000j],
       [ 0.707-0.293j],
       [ 1.000+1.000j],
       [-0.707+1.707j]])

In [42]:
N=8
for k in range(8):
    exp = np.array([np.exp((-2*np.pi*(1j)/N)*k*x) for x in np.arange(N)])
    F_print = np.dot(exp, given_array)
    F_print = np.around(F_print, 3)
    print(f' index is i={k} F{k} is {F_print}')

 index is i=0 F0 is (6+0j)
 index is i=1 F1 is (-0.707-1.707j)
 index is i=2 F2 is (1-1j)
 index is i=3 F3 is (0.707+0.293j)
 index is i=4 F4 is -0j
 index is i=5 F5 is (0.707-0.293j)
 index is i=6 F6 is (1+1j)
 index is i=7 F7 is (-0.707+1.707j)
